### PR TITLE
Model validation

### LINKED ISSUE #43: Validation for Models
- [x] Add a ValidationTask object

- [x] Add validation rules

- [x] Set up validate method

- [x] Use same exceptions API

### PR DESCRIPTION
**Pull request by li-kai**
Fixes #43

Not entirely sure if its `IllegalValueException` or `ValidationException` that should be thrown

### CODE REVIEW

File: src/main/java/seedu/todo/model/task/ValidationTask.java [hunk 1]
```diff
@@ -0,0 +1,187 @@
...
+import java.util.Optional;
+import java.util.Set;
+import java.util.UUID;
+
+import seedu.todo.commons.exceptions.ValidationException;
+import seedu.todo.model.ErrorBag;
+import seedu.todo.model.tag.Tag;
+
+public class ValidationTask implements ImmutableTask, MutableTask {
+    private static final String TITLE = "title";
```
Comment (ZhangYiJiang) [inline src/main/java/seedu/todo/model/task/ValidationTask.java]: These error messages need to be displayed to the user

File: src/main/java/seedu/todo/model/task/ValidationTask.java [hunk 2]
```diff
@@ -0,0 +1,187 @@
...
+     * Validates the task by checking the individual fields are valid.
+     */
+    public void validate() throws ValidationException {
+        isValidTime();
+        isValidTitle();
+        errors.validate(VALIDATION_ERROR_MESSAGE);
+    }
+
+    private void isValidTitle() {
+        if (title.isEmpty()) {
```
Comment (ZhangYiJiang) [inline src/main/java/seedu/todo/model/task/ValidationTask.java]: Use `StringUtil.isEmpty`

File: src/main/java/seedu/todo/model/task/ValidationTask.java [hunk 3]
```diff
@@ -0,0 +1,187 @@
...
+            errors.put(TITLE, TITLE_EMPTY_ERROR_MESSAGE);
+        }
+    }
+
+    /**
+     * Validates time. Only valid when
+     * 1) both time fields are not declared
```
Comment (ZhangYiJiang) [inline src/main/java/seedu/todo/model/task/ValidationTask.java:74]: Incorrect. Tasks have only `endTime`.

File: src/test/java/seedu/todo/model/TodoTest.java [hunk 4]
```diff
@@ -97,30 +106,54 @@ public void testUpdate() throws IllegalValueException {
...
+            t.setStartTime(LocalDateTime.now());
+            t.setEndTime(LocalDateTime.now().plusHours(4));
+        });
+        todo.update(task, t -> t.setEndTime(LocalDateTime.now()));
+    }
+
+    @Test
+    public void testSorting() throws Exception {
         LocalDateTime now = LocalDateTime.now();
-        todo.add("Task 3", p -> p.setEndTime(now));
```
Comment (ZhangYiJiang) [inline src/test/java/seedu/todo/model/TodoTest.java:104]: These changes to the test is unnecessary. Please revert.

File: src/test/java/seedu/todo/model/task/ValidationTaskTest.java [hunk 5]
```diff
@@ -0,0 +1,188 @@
...
+        task.setLocation("Some Test Location");
+        assertEquals("Some Test Location", task.getLocation().get());
+    }
+
+    @Test
+    public void testTime() {
+        assertFalse(task.getStartTime().isPresent());
+        assertFalse(task.getEndTime().isPresent());
+
+        // TODO: Time definitely needs validation, for example task end time
```
Comment (ZhangYiJiang) [inline src/test/java/seedu/todo/model/task/ValidationTaskTest.java]: Please don't blindly copy and paste code without at least reading through them first

**Review by ZhangYiJiang — CHANGES_REQUESTED** [review]
