### PR TITLE
Find command bug

### LINKED ISSUE #148: View command should reset find
Find view doesn't go back to non-find view after adding a task or other commands.

### PR DESCRIPTION
**Pull request by cricketer94**
Fixes #148 and part of #162 . Do let me know if it's too 'hacky'

### CODE REVIEW

File: src/main/java/seedu/todo/logic/commands/FindCommand.java [hunk 1]
```diff
@@ -13,7 +13,7 @@
 import java.util.function.Predicate;
 
 public class FindCommand extends BaseCommand {
-    private static final String FEEDBACK = "Type 'find' again to close find";
+    private static final String FEEDBACK = "Type 'find' or switch to another view to close find";
```
Comment (xiendong) [inline src/main/java/seedu/todo/logic/commands/FindCommand.java]: close find sounds funny though... dismiss?

File: src/main/java/seedu/todo/logic/commands/ViewCommand.java [hunk 2]
```diff
@@ -58,6 +58,7 @@ protected void validateArguments() {
 
     @Override
     public CommandResult execute() throws ValidationException {
+        model.find(null);
```
Comment (xiendong) [inline src/main/java/seedu/todo/logic/commands/ViewCommand.java:62]: Not immediately intuitive what this is doing though

File: src/main/java/seedu/todo/logic/commands/FindCommand.java [hunk 3]
```diff
@@ -13,7 +13,7 @@
 import java.util.function.Predicate;
 
 public class FindCommand extends BaseCommand {
-    private static final String FEEDBACK = "Type 'find' again to close find";
+    private static final String FEEDBACK = "Type 'find' or switch to another view to dismiss find results";
```
Comment (xiendong) [inline src/main/java/seedu/todo/logic/commands/FindCommand.java:17]: find results sound weird... but it's fine if there are no major issues below

File: src/main/java/seedu/todo/model/TodoModel.java [hunk 4]
```diff
@@ -193,7 +193,6 @@ public ImmutableTask update(int index, Consumer<MutableTask> update) throws Vali
     @Override
     public void view(TaskViewFilter view) {
         viewFilteredTasks.setPredicate(view.filter);
-
         sortedTasks.setComparator((a, b) -> {
             int pin = Boolean.compare(b.isPinned(), a.isPinned());
             return pin != 0 || view.sort == null ? pin : view.sort.compare(a, b);
```
Comment (xiendong) [inline src/main/java/seedu/todo/model/TodoModel.java:198]: Styling issue: too much math hack, I can't understand this :/

File: src/main/java/seedu/todo/ui/view/TodoListView.java [hunk 5]
```diff
@@ -84,11 +84,16 @@ private void setConnections(ObservableList<ImmutableTask> todoList) {
...
      */
-    public void toggleExpandCollapsed(ImmutableTask task) {
+    public void toggleExpandCollapsed(ImmutableTask task, Boolean toCollapse) {
         TaskCardView taskCardView = TaskCardView.getTaskCard(task);
-        if (taskCardView != null) {
+        if (taskCardView != null && toCollapse == null) {
             taskCardView.toggleCardCollapsing();
         }
+        else if (taskCardView != null && toCollapse != null) {
+            //unbox boolean
```
Comment (xiendong) [inline src/main/java/seedu/todo/ui/view/TodoListView.java]: I think this comment not necessary? :/

File: src/main/java/seedu/todo/ui/view/TodoListView.java [hunk 6]
```diff
@@ -84,11 +84,16 @@ private void setConnections(ObservableList<ImmutableTask> todoList) {
...
+            boolean isCollapsing = toCollapse;
```
Comment (xiendong) [inline src/main/java/seedu/todo/ui/view/TodoListView.java]: hmmmmmmm... I think you can find a way to do away this declaration

File: src/main/java/seedu/todo/ui/view/TodoListView.java [hunk 7]
```diff
@@ -97,7 +102,10 @@ public void toggleExpandCollapsed(ImmutableTask task) {
     public void scrollAndSelect(int listIndex) {
         Platform.runLater(() -> {
             todoListView.scrollTo(listIndex);
+            System.out.println("Scrolled to selected Index");
```
Comment (xiendong) [inline src/main/java/seedu/todo/ui/view/TodoListView.java]: Delete sysout calls.

File: src/main/java/seedu/todo/ui/view/TodoListView.java [hunk 8]
```diff
@@ -97,7 +102,10 @@ public void toggleExpandCollapsed(ImmutableTask task) {
...
             todoListView.getSelectionModel().clearAndSelect(listIndex);
+            System.out.println("We have selected the current Index provided");
```
Comment (xiendong) [inline src/main/java/seedu/todo/ui/view/TodoListView.java]: Same here

File: src/main/java/seedu/todo/ui/view/TodoListView.java [hunk 9]
```diff
@@ -120,7 +128,7 @@ private void scrollAndSelectHelper(ImmutableTask task, int attempts) {
             TaskCardView taskCardView = TaskCardView.getTaskCard(task);
             if (taskCardView != null) {
                 int listIndex = FxViewUtil.convertToListIndex(taskCardView.getDisplayedIndex());
-                scrollAndSelect(listIndex);
+                scrollAndSelect(listIndex);
```
Comment (xiendong) [inline src/main/java/seedu/todo/ui/view/TodoListView.java]: You added a space by accident

File: src/main/java/seedu/todo/logic/commands/FindCommand.java (hunk 3 above)
Comment (xiendong) [reply src/main/java/seedu/todo/logic/commands/FindCommand.java:17]: Type "find" to dismiss.
